// try
// {
//     console.log(hellosss);
// }
// catch (err)
// {
//     console.log(err, 'this is the exception thrown');
// }

